name: Action 🎲

on:
  push:
    branches:
      - main
      - develop

jobs:
  Action:
    name: Action 🎲
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Start
        run: echo "continue"
      - name: ⚪ Checkout repo
        uses: actions/checkout@master
      - name: 🟩 Setup PNPM
        uses: pnpm/action-setup@master
        with:
          version: 7
      - name: 🟢 Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
      - name: Install Packages
        run: time pnpm install
        # run: time yarn install
        # run: time yarn install --frozen-lockfile # cache installs
      - name: 🔢 Run Standards
        run: pnpm check-all
        # run: yarn check-all
      - name: 🧪 Run Test
        run: pnpm test
        # run: yarn test
      - name: 📦 Run Build
        run: pnpm build
        # run: yarn build
      # use only for main branch
      # - name: 📏 Run Benchmarks
        # run: yarn load:lighthouse
      - name: Finish
        run: echo "done"

# how to use pnpm in gh actions
# how to cashe using package lock-file for CI
